/*$file${AOs::.::Blinky.h} #################################################*/
/*
* Model: Blinky.qm
* File:  ${AOs::.::Blinky.h}
*
* This code has been generated by QM 4.3.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${AOs::.::Blinky.h} ##############################################*/

#include "qpc.h"

/*$declare${AOs::Blinky} ###################################################*/
/*${AOs::Blinky} ...........................................................*/
typedef struct {
/* protected: */
    QActive super;

/* private: */
    QTimeEvt timeEvt;
} Blinky;

/* protected: */
QState Blinky_initial(Blinky * const me, QEvt const * const e);
QState Blinky_led1_On(Blinky * const me, QEvt const * const e);
QState Blinky_led1_Off(Blinky * const me, QEvt const * const e);
QState Blinky_led2_On(Blinky * const me, QEvt const * const e);
QState Blinky_led2_Off(Blinky * const me, QEvt const * const e);
/*$enddecl${AOs::Blinky} ###################################################*/

extern Blinky l_blinky;
