/*$file${AOs::.::Blinky.c} #################################################*/
/*
* Model: Blinky.qm
* File:  ${AOs::.::Blinky.c}
*
* This code has been generated by QM 4.3.1 (https://www.state-machine.com/qm).
* DO NOT EDIT THIS FILE MANUALLY. All your changes will be lost.
*
* This program is open source software: you can redistribute it and/or
* modify it under the terms of the GNU General Public License as published
* by the Free Software Foundation.
*
* This program is distributed in the hope that it will be useful, but
* WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
* or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License
* for more details.
*/
/*$endhead${AOs::.::Blinky.c} ##############################################*/
#include "qpc.h"
#include <stdio.h>
#include <stdlib.h>
#include "Blinky.h"
#include "bsp.h"

enum BlinkySignals {
    TIMEOUT_SIG = Q_USER_SIG,
    MAX_SIG
};

Blinky l_blinky;

/* Check for the minimum required QP version */
#if (QP_VERSION < 630U) || (QP_VERSION != ((QP_RELEASE^4294967295U) % 0x3E8U))
#error qpc version 6.3.0 or higher required
#endif

/*$define${AOs::Blinky} ####################################################*/
/*${AOs::Blinky} ...........................................................*/
/*${AOs::Blinky::SM} .......................................................*/
QState Blinky_initial(Blinky * const me, QEvt const * const e) {
    /*${AOs::Blinky::SM::initial} */
    QTimeEvt_postEvery(&me->timeEvt, (QActive *)me, BSP_TICKS_PER_SEC/2);
    return Q_TRAN(&Blinky_led1_On);
}
/*${AOs::Blinky::SM::led1_On} ..............................................*/
QState Blinky_led1_On(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::led1_On} */
        case Q_ENTRY_SIG: {
            BSP_led1_On();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::led1_On::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_led1_Off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Blinky::SM::led1_Off} .............................................*/
QState Blinky_led1_Off(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::led1_Off} */
        case Q_ENTRY_SIG: {
            BSP_led1_Off();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::led1_Off::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_led2_On);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Blinky::SM::led2_On} ..............................................*/
QState Blinky_led2_On(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::led2_On} */
        case Q_ENTRY_SIG: {
            BSP_led2_On();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::led2_On::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_led2_Off);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*${AOs::Blinky::SM::led2_Off} .............................................*/
QState Blinky_led2_Off(Blinky * const me, QEvt const * const e) {
    QState status_;
    switch (e->sig) {
        /*${AOs::Blinky::SM::led2_Off} */
        case Q_ENTRY_SIG: {
            BSP_led2_Off();
            status_ = Q_HANDLED();
            break;
        }
        /*${AOs::Blinky::SM::led2_Off::TIMEOUT} */
        case TIMEOUT_SIG: {
            status_ = Q_TRAN(&Blinky_led1_On);
            break;
        }
        default: {
            status_ = Q_SUPER(&QHsm_top);
            break;
        }
    }
    return status_;
}
/*$enddef${AOs::Blinky} ####################################################*/

